### ISSUE TITLE
By default mount the database in-memory

### ISSUE THREAD

**Issue by robert-bor** [42BV/spring-boot-docker-postgres#29]
@SanderBenschop used this for his project:

```
docker:
  postgres:
    container-name: application-unit-test
    docker-command: 'docker run --rm --tty -e POSTGRES_PASSWORD=postgres -p ${port}:5432 --name ${containerName} --mount type=tmpfs,destination=/app --mount type=tmpfs,destination=/var/lib/postgresql/data ${imageName}:${imageVersion}'
```

This speeded up the database considerably which is a big plus for unit tests. Make sure that the mount is the default and offer a variable to disable the in-memory option.

**Comment by robert-bor** [comment]
Approach will be to offer two more configurable settings:
* **in-memory**; will by default be true. Determines if destinations must be mounted to the in-memory configuration. 
* **in-memory-mount-destinations**; will by default contain ```/app``` and ```/var/lib/postgresql/data```. Can be overridden in case an another image with different folders is used.

In YML, will look like this:

```
docker:
  postgres:
    in-memory: true
    in-memory-mount-destinations:
      - /app
      - /var/lib/postgresql/data
```
